best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/100leaves.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/NUS_v2.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
- config/YaleB.yaml
- config/YaleB_F10.yaml
dataset_args:
  mat_path: data/YaleB.mat
  topk: 6
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/YaleB.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/YaleB
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.9984615399999999
  std: 0.004615379999999991
metric_f1:
  mean: 0.9985641025641027
  std: 0.004307692307692313
metric_precision:
  mean: 0.99875
  std: 0.0037499999999999873
metric_recall:
  mean: 0.9985714285714286
  std: 0.00428571428571427
model_args:
  alpha: 0.1
  hid_dim: 64
  lamda: 0.5
  n_layer: 46
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/YaleB
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.9357265
  std: 0.019191027486245238
val_metric_f1:
  mean: 0.9350646089283566
  std: 0.01932277103601264
val_metric_precision:
  mean: 0.9416682868968888
  std: 0.018240038807000966
val_metric_recall:
  mean: 0.9354802259887005
  std: 0.019195352076788755
