best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/NGs.yaml
dataset_args:
  mat_path: data/BBCSports.mat
  topk: 9
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/BBCSports.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/BBCSports
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 1.0
  std: 0.0
metric_f1:
  mean: 1.0
  std: 0.0
metric_precision:
  mean: 1.0
  std: 0.0
metric_recall:
  mean: 1.0
  std: 0.0
model_args:
  alpha: 0.1
  hid_dim: 48
  lamda: 0.5
  n_layer: 56
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/BBCSports
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.955306111
  std: 0.007875011201574826
val_metric_f1:
  mean: 0.9609968031397826
  std: 0.008221529033124413
val_metric_precision:
  mean: 0.9604748592861874
  std: 0.009047418475459926
val_metric_recall:
  mean: 0.964599982562728
  std: 0.007387185362041137
