best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/100leaves.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/NUS_v2.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
- config/YaleB.yaml
- config/YaleB_F10.yaml
- config/Youtube.yaml
- config/HW.yaml
- config/animals.yaml
dataset_args:
  mat_path: data/MNIST.mat
  topk: 6
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/MNIST.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/MNIST
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.9959999999999999
  std: 0.006244997998398403
metric_f1:
  mean: 0.9961408812401439
  std: 0.006004564892805991
metric_precision:
  mean: 0.9962987012987015
  std: 0.005809138315349966
metric_recall:
  mean: 0.9961428571428572
  std: 0.005975004625279266
model_args:
  alpha: 0.1
  hid_dim: 56
  lamda: 0.5
  n_layer: 3
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/MNIST
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.925944449
  std: 0.008570874635225326
val_metric_f1:
  mean: 0.9106109645785578
  std: 0.009193293746752507
val_metric_precision:
  mean: 0.9087612799987557
  std: 0.009302392078888232
val_metric_recall:
  mean: 0.9176306720380796
  std: 0.00804894817492521
