best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/YaleB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
dataset_args:
  mat_path: data/MNIST.mat
  topk: 6
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/MNIST.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/MNIST
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.9719999999999999
  std: 0.014177446878757837
metric_f1:
  mean: 0.9719029918193058
  std: 0.014136856622023844
metric_precision:
  mean: 0.9737182795592407
  std: 0.01298970538250119
metric_recall:
  mean: 0.9717916666666666
  std: 0.014243550127622465
model_args:
  alpha: 0.1
  hid_dim: 32
  lamda: 0.5
  n_layer: 6
  num_heads: 1
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/MNIST
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.9293889080000002
  std: 0.005428826535832227
val_metric_f1:
  mean: 0.9158879305083403
  std: 0.0049176144337665035
val_metric_precision:
  mean: 0.913728967619846
  std: 0.005182276744370076
val_metric_recall:
  mean: 0.9210275337352749
  std: 0.004822296367156183
