best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/YaleB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
dataset_args:
  mat_path: data/MNIST.mat
  topk: 6
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/MNIST.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/MNIST
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.9949999999999999
  std: 0.007071067811865481
metric_f1:
  mean: 0.9951789428193285
  std: 0.00682587820814152
metric_precision:
  mean: 0.9953246753246754
  std: 0.0066427298387240485
metric_recall:
  mean: 0.9952380952380953
  std: 0.006734350297014722
model_args:
  alpha: 0.1
  hid_dim: 88
  lamda: 0.5
  n_layer: 6
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/MNIST
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.9299999999999999
  std: 0.0119205147685123
val_metric_f1:
  mean: 0.9175270507817714
  std: 0.014331067108962958
val_metric_precision:
  mean: 0.9172817400133313
  std: 0.013680255237905746
val_metric_recall:
  mean: 0.9219444333849932
  std: 0.012697094771028972
