best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/YaleB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
dataset_args:
  mat_path: data/WebKB_wisconsin.mat
  topk: 71
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/WebKB_wisconsin.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/WebKB_wisconsin
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 1.0
  std: 0.0
metric_f1:
  mean: 1.0
  std: 0.0
metric_precision:
  mean: 1.0
  std: 0.0
metric_recall:
  mean: 1.0
  std: 0.0
model_args:
  alpha: 0.1
  hid_dim: 88
  lamda: 0.5
  n_layer: 30
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/WebKB_wisconsin
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.7523012710000001
  std: 0.011195887881585312
val_metric_f1:
  mean: 0.5297361675704548
  std: 0.013370032542417937
val_metric_precision:
  mean: 0.6796835211285164
  std: 0.028470938673899743
val_metric_recall:
  mean: 0.6317463054187191
  std: 0.015329237092565418
