best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/HW.yaml
dataset_args:
  mat_path: data/HW.mat
  topk: 6
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/HW.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/HW
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 1.0
  std: 0.0
metric_f1:
  mean: 1.0
  std: 0.0
metric_precision:
  mean: 1.0
  std: 0.0
metric_recall:
  mean: 1.0
  std: 0.0
model_args:
  alpha: 0.1
  hid_dim: 56
  lamda: 0.5
  n_layer: 40
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/HW
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.9772777640000001
  std: 0.0027040196507651343
val_metric_f1:
  mean: 0.9773371315833236
  std: 0.0026887304265584885
val_metric_precision:
  mean: 0.9777822080042038
  std: 0.0026624154940833025
val_metric_recall:
  mean: 0.9772553398255843
  std: 0.0026933303332162565
