best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/YaleB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
dataset_args:
  mat_path: data/WebKB_texas.mat
  topk: 14
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/WebKB_texas.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/WebKB_texas
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.9285713999999998
  std: 2.220446049250313e-16
metric_f1:
  mean: 0.7272727272727273
  std: 0.0
metric_precision:
  mean: 0.7083333333333333
  std: 1.1102230246251565e-16
metric_recall:
  mean: 0.75
  std: 0.0
model_args:
  alpha: 0.1
  hid_dim: 80
  lamda: 0.5
  n_layer: 38
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/WebKB_texas
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.29826589800000003
  std: 0.013968841662018951
val_metric_f1:
  mean: 0.32499367456995093
  std: 0.014297315312779496
val_metric_precision:
  mean: 0.3793039874522857
  std: 0.04129838693910241
val_metric_recall:
  mean: 0.49652014652014653
  std: 0.029284677676275284
