best_trial: 1
best_trial_save_dir: temp_result/
config_paths:
- config/MNIST10k.yaml
dataset_args:
  mat_path: data/MNIST10k.mat
  topk: 10
  train_ratio: 0.1
device: cpu
dfcallback_args:
  df_save_path: ./tables/MNIST10k.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/MNIST10k
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.965
  std: 0.0
metric_f1:
  mean: 0.9650285778470844
  std: 0.0
metric_precision:
  mean: 0.9653659404355804
  std: 0.0
metric_recall:
  mean: 0.9649125412541254
  std: 0.0
model_args:
  alpha: 0.1
  hid_dim: 64
  lamda: 0.5
  n_layer: 14
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
result_dir: temp_result/
run_times: 1
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/MNIST10k
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.9438889
  std: 0.0
val_metric_f1:
  mean: 0.9427730734519456
  std: 0.0
val_metric_precision:
  mean: 0.943415366673501
  std: 0.0
val_metric_recall:
  mean: 0.9425379920673091
  std: 0.0
