best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/100leaves.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/NUS_v2.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
- config/YaleB.yaml
- config/YaleB_F10.yaml
- config/Youtube.yaml
- config/HW.yaml
- config/animals.yaml
dataset_args:
  mat_path: data/100leaves.mat
  topk: 14
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/100leaves.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/100leaves
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.046
  std: 0.006511528238439883
metric_f1:
  mean: 0.026535585313982556
  std: 0.005538403119191049
metric_precision:
  mean: 0.0298052332801103
  std: 0.006621881273084783
metric_recall:
  mean: 0.038720538720538676
  std: 0.0054810843757911445
model_args:
  alpha: 0.1
  hid_dim: 64
  lamda: 0.5
  n_layer: 12
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/100leaves
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.044962962999999995
  std: 0.02089374757901867
val_metric_f1:
  mean: 0.01730892781686271
  std: 0.012186379728900696
val_metric_precision:
  mean: 0.01764045783742564
  std: 0.013141320496484907
val_metric_recall:
  mean: 0.046692307692307644
  std: 0.02169735347753255
