best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/100leaves.yaml
dataset_args:
  mat_path: data/100leaves.mat
  topk: 6
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/100leaves.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/100leaves
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.603658536
  std: 0.17383218833623754
metric_f1:
  mean: 0.5608265051446869
  std: 0.17361660404847293
metric_precision:
  mean: 0.5939805985260531
  std: 0.1814505851085476
metric_recall:
  mean: 0.5897306397306397
  std: 0.17453463680261558
model_args:
  alpha: 0.1
  hid_dim: 128
  lamda: 0.5
  n_layer: 64
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/100leaves
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.490694228
  std: 0.1200974334659274
val_metric_f1:
  mean: 0.4524459539320856
  std: 0.12537543678142996
val_metric_precision:
  mean: 0.48654304572182916
  std: 0.13369049868819752
val_metric_recall:
  mean: 0.4959560439560439
  std: 0.11999220378812606
