best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/YaleB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
dataset_args:
  mat_path: data/GRAZ02.mat
  topk: 36
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/GRAZ02.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/GRAZ02
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.310884356
  std: 0.019011141720560707
metric_f1:
  mean: 0.2276965359184567
  std: 0.031194355235698218
metric_precision:
  mean: 0.3401929850709436
  std: 0.11523868099447641
metric_recall:
  mean: 0.30889250152408043
  std: 0.018205990822168273
model_args:
  alpha: 0.1
  hid_dim: 56
  lamda: 0.5
  n_layer: 57
  num_heads: 8
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/GRAZ02
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.27261098
  std: 0.03686068527569719
val_metric_f1:
  mean: 0.13827386586861343
  std: 0.04380055450548029
val_metric_precision:
  mean: 0.114267587931672
  std: 0.05391292099135029
val_metric_recall:
  mean: 0.26303179051239856
  std: 0.02048883751899658
