best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/100leaves.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/NUS_v2.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
- config/YaleB.yaml
- config/YaleB_F10.yaml
dataset_args:
  mat_path: data/GRAZ02.mat
  topk: 34
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/GRAZ02.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/GRAZ02
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.303401359
  std: 0.02218980688021707
metric_f1:
  mean: 0.22446587115548372
  std: 0.049152648194306314
metric_precision:
  mean: 0.3324961871077489
  std: 0.12143143222584148
metric_recall:
  mean: 0.3031106183582964
  std: 0.02462682353085202
model_args:
  alpha: 0.1
  hid_dim: 24
  lamda: 0.5
  n_layer: 28
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/GRAZ02
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.246651613
  std: 0.03315168790250025
val_metric_f1:
  mean: 0.10678721744741422
  std: 0.0299240526631885
val_metric_precision:
  mean: 0.09860580250003684
  std: 0.08241195280956629
val_metric_recall:
  mean: 0.25374960747560793
  std: 0.00988857191751369
