best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/100leaves.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/NUS_v2.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
- config/YaleB.yaml
- config/YaleB_F10.yaml
- config/Youtube.yaml
- config/HW.yaml
- config/animals.yaml
dataset_args:
  mat_path: data/GRAZ02.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/GRAZ02.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/GRAZ02
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.29183673599999993
  std: 0.030943037184574557
metric_f1:
  mean: 0.22860285050353574
  std: 0.04865619450651643
metric_precision:
  mean: 0.3828801218688627
  std: 0.1149791177813731
metric_recall:
  mean: 0.2928115615615615
  std: 0.03047766619095461
model_args:
  alpha: 0.1
  hid_dim: 48
  lamda: 0.5
  n_layer: 7
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/GRAZ02
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.25161775999999997
  std: 0.026236941986489203
val_metric_f1:
  mean: 0.11432113553753738
  std: 0.026197923861406174
val_metric_precision:
  mean: 0.11439541439620297
  std: 0.09507604665064404
val_metric_recall:
  mean: 0.2518108393443265
  std: 0.00397430656139503
