best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/YaleB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
dataset_args:
  mat_path: data/ORL2.mat
  topk: 7
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/ORL2.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/ORL2
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.980357141
  std: 0.03139000090208326
metric_f1:
  mean: 0.9753846153846155
  std: 0.04272273326991681
metric_precision:
  mean: 0.9764957264957266
  std: 0.04295881583889824
metric_recall:
  mean: 0.9794871794871796
  std: 0.0349696966589381
model_args:
  alpha: 0.1
  hid_dim: 96
  lamda: 0.5
  n_layer: 24
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/ORL2
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.799127906
  std: 0.024406481488943546
val_metric_f1:
  mean: 0.785856071121193
  std: 0.027376173531547063
val_metric_precision:
  mean: 0.8232507050912623
  std: 0.02113255288361676
val_metric_recall:
  mean: 0.8072222222222221
  std: 0.023955213162364476
