best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/100leaves.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/NUS_v2.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
- config/YaleB.yaml
- config/YaleB_F10.yaml
dataset_args:
  mat_path: data/ORL2.mat
  topk: 90
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/ORL2.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/ORL2
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.1320754734
  std: 0.022324829252184663
metric_f1:
  mean: 0.06004543386896324
  std: 0.01002826359755864
metric_precision:
  mean: 0.0585914655145424
  std: 0.00651059242904903
metric_recall:
  mean: 0.0897435897435897
  std: 0.015169435341281044
model_args:
  alpha: 0.1
  hid_dim: 48
  lamda: 0.5
  n_layer: 1
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/ORL2
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.050144092099999996
  std: 0.01972327210826793
val_metric_f1:
  mean: 0.012353235173342348
  std: 0.009802958853792551
val_metric_precision:
  mean: 0.01156043344043363
  std: 0.011110586607830738
val_metric_recall:
  mean: 0.05437500000000001
  std: 0.021387423290335845
