best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
- config/100leaves.yaml
- config/BBCnews.yaml
- config/BBCSports.yaml
- config/COIL20.yaml
- config/GRAZ02.yaml
- config/MNIST.yaml
- config/NGs.yaml
- config/NUS_v2.yaml
- config/ORL2.yaml
- config/ORL_v3.yaml
- config/WebKB.yaml
- config/WebKB_wisconsin.yaml
- config/WebKB_cornell.yaml
- config/WebKB_texas.yaml
- config/WebKB_washington.yaml
- config/YaleB.yaml
- config/YaleB_F10.yaml
dataset_args:
  mat_path: data/ORL_v3.mat
  topk: 7
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/ORL_v3.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/ORL_v3
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.7421052770000001
  std: 0.2539985048563324
metric_f1:
  mean: 0.6842572242572242
  std: 0.27743969837308413
metric_precision:
  mean: 0.6840842490842489
  std: 0.2831327601140189
metric_recall:
  mean: 0.7128205128205128
  std: 0.2698527613727768
model_args:
  alpha: 0.1
  hid_dim: 56
  lamda: 0.5
  n_layer: 37
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/ORL_v3
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 25
val_metric_acc:
  mean: 0.613702619
  std: 0.19654233163113144
val_metric_f1:
  mean: 0.5768397094666363
  std: 0.21985275487077174
val_metric_precision:
  mean: 0.609744759966898
  std: 0.24556758614090055
val_metric_recall:
  mean: 0.6246875000000001
  std: 0.19458145284700817
