best_trial: 5
best_trial_save_dir: best/
config_paths:
- config/NUS_v2.yaml
dataset_args:
  mat_path: data/NUS_v2.mat
  topk: 7
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/NUS_v2.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/NUS_v2
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights:
- 0.66
- 1.0e-06
- 1.0e-06
metric_acc:
  mean: 0.836666666
  std: 0.05013176802742954
metric_f1:
  mean: 0.836079173489761
  std: 0.05090651778709752
metric_precision:
  mean: 0.843023818420308
  std: 0.04746596696492895
metric_recall:
  mean: 0.8398977411477413
  std: 0.04926766000134507
model_args:
  alpha: 0.1
  hid_dim: 40
  lamda: 0.5
  n_layer: 1
model_class_args:
  class_name: AttModel
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/NUS_v2
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 1
val_metric_acc:
  mean: 0.37740740799999994
  std: 0.010931811656695165
val_metric_f1:
  mean: 0.3722664946834221
  std: 0.010313985302711985
val_metric_precision:
  mean: 0.39028416789238907
  std: 0.011921964236700524
val_metric_recall:
  mean: 0.3766585963147744
  std: 0.01090142907518125
